name: Create release

# Controls when the action will run
# Option bellow allows you to run the workflow manually
on:
  push:
    branches:
      - main
  workflow_dispatch:
#    inputs:
#      release_version:
#        description: 'Release new version'

# Allow GitHub Actions to push changes to the repository
permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # Setup git config of the GitHub Actions Bot
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      # Run release task
      - name: Release with Gradle Release Plugin
        run: ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=1.0.0 -Prelease.newVersion=1.1.0-SNAPSHOT