name: Create release

# Controls when the action will run
# Option bellow allows you to run the workflow manually
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release new version'

# Allow GitHub Actions to push changes to the repository
permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - run: ./gradlew release

      # Setup git config of the GitHub Actions Bot
      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "vasili.atrokhau@gmail.com"

      # Run release task
      - name: Release with Gradle Release Plugin
        run: ./gradlew release